# Changes here will be overwritten by Copier
_commit: d292869
_src_path: https://github.com/oarepo/nrp-app-copier
languages: ''
repository_description: My Repository description
repository_human_name: My Repository
use_ccmm: true
